# Generated by Django 3.1.13 on 2025-02-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20250205_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_per_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='last_sales_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_sold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
